# Generated by Django 4.0 on 2022-08-11 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tradition',
            table='Tradition',
        ),
    ]
